--1
SELECT 
    NUMRUN_CLI AS "RUN CLIENTE",
    PNOMBRE_CLI || ' ' ||
    SNOMBRE_CLI || ' ' ||
    APPATERNO_CLI || ' ' ||
    APMATERNO_CLI AS "NOMBRE COMPLETO",
    TO_CHAR(FECHA_NAC_CLI, 'dd/mm/yyyy') AS "FECHA DE NACIMIENTO"
FROM CLIENTE
WHERE EXTRACT(DAY FROM FECHA_NAC_CLI)= 21 and EXTRACT (MONTH FROM FECHA_NAC_CLI)= 08 
ORDER BY APPATERNO_CLI ASC;
------------------------------------------
--2
SELECT 
    NUMRUN_EMP AS "RUN EMPLEADO",
    PNOMBRE_EMP || ' ' ||
    SNOMBRE_EMP || ' ' ||
    APPATERNO_EMP || ' ' ||
    APMATERNO_EMP AS "NOMBRE COMPLETO EMPLEADO",
    TRUNC(SUELDO_BASE/100000) AS "PORCENTAJE DE MOVILIZACIÓN",
    ROUND(TRUNC(SUELDO_BASE/100000)/100 * SUELDO_BASE) AS "VALOR MOVILIZACIÓN"
FROM EMPLEADO
ORDER BY TRUNC(SUELDO_BASE/100000) DESC;
------------------------------------------
--3
SELECT
    NUMRUN_EMP || '-' ||
    DVRUN_EMP AS "RUN EMPLEADO",
    PNOMBRE_EMP || ' ' ||
    SNOMBRE_EMP || ' ' ||
    APPATERNO_EMP || ' ' ||
    APMATERNO_EMP AS "NOMBRE COMPLETO EMPLEADO",
    SUELDO_BASE AS "SUELDO BASE",
    TO_CHAR (FECHA_NAC, 'dd/mm/yyyy') AS "FECHA DE NACIMIENTO",
    SUBSTR(PNOMBRE_EMP,1,3)|| '' ||
    LENGTH(PNOMBRE_EMP)|| '*' ||
    SUBSTR(TO_CHAR(SUELDO_BASE),
    LENGTH(SUELDO_BASE))||
    DVRUN_EMP||
    TRUNC((MONTHS_BETWEEN(SYSDATE,FECHA_CONTRATO))/12) AS "NOMBRE DE USUARIO",
    SUBSTR(NUMRUN_EMP,3,1)||
    EXTRACT(YEAR FROM FECHA_CONTRATO)+2||
    SUBSTR(SUELDO_BASE,-3)-1||
    SUBSTR(APPATERNO_EMP,-2)||
    EXTRACT(MONTH FROM SYSDATE) AS "CLAVE"
FROM EMPLEADO
ORDER BY APPATERNO_EMP ASC;
-------------------------------------------
--4
SELECT
    EXTRACT(YEAR FROM SYSDATE) AS "ANNO_PROCESO",
    NRO_PATENTE,
    VALOR_ARRIENDO_DIA AS "VALOR_ARRIENDO_DIA_SR",
    VALOR_GARANTIA_DIA AS "VALOR_GARANTIA_DIA_SR",
    EXTRACT(YEAR FROM SYSDATE) - ANIO AS "AÑOS_DE_ANTIGUEDAD",
    VALOR_ARRIENDO_DIA-(VALOR_ARRIENDO_DIA * ((EXTRACT(YEAR FROM SYSDATE) - ANIO)/100)) AS "VALOR_ARRIENDO_DIA_CR",
    VALOR_GARANTIA_DIA-(VALOR_GARANTIA_DIA * ((EXTRACT(YEAR FROM SYSDATE) - ANIO)/100)) AS "VALOR_GARANTIA_DIA_CR"
FROM CAMION
WHERE EXTRACT(YEAR FROM SYSDATE) - ANIO > 5
ORDER BY EXTRACT(YEAR FROM SYSDATE) - ANIO DESC, NRO_PATENTE ASC;
-------------------------------------------
--5
SELECT
    EXTRACT(MONTH FROM FECHA_INI_ARRIENDO) ||'/'|| EXTRACT(YEAR FROM FECHA_INI_ARRIENDO) AS "MES_ANNO_PROCESO",
    NRO_PATENTE,
    FECHA_INI_ARRIENDO,
    DIAS_SOLICITADOS,
    FECHA_DEVOLUCION
FROM ARRIENDO_CAMION;