--CASO 1
SELECT
    CARRERAID AS "IDENTIFICACION DE LA CARRERA",
    COUNT(CARRERAID) AS "TOTAL ALUMNOS MATRICULADOS",
    'Le CORRESPONDEN'||TO_CHAR(COUNT(CARRERAID)*30200,'$999G999G999')||' del presupuesto total asignado para publicidad.' AS "MONTO POR PUBLICIDAD"
FROM ALUMNO
GROUP BY CARRERAID
ORDER BY  COUNT(CARRERAID) DESC,CARRERAID;

--CASO 2
SELECT
    CARRERAID AS "CARRERA",
    COUNT(CARRERAID) AS "TOTAL DE ALUMNOS"
FROM ALUMNO
HAVING COUNT(CARRERAID) > 4
GROUP BY CARRERAID
ORDER BY CARRERAID;

--Caso 3
SELECT
    TO_CHAR(RUN_JEFE,'99G999G999') AS "RUN JEFE SIN DV",
    COUNT(RUN_EMP) AS "TOTAL DE EMPLEADOS A SU CARGO",
    TO_CHAR(MAX(SALARIO),'$999G999G999') AS "SALARIO MAXIMO",
    COUNT(RUN_EMP) * 10 ||'% del Salario Máximo' AS "PORCENTAJE DE BONIFICACIÓN",
    TO_CHAR(MAX(SALARIO) * (COUNT(RUN_EMP)) * 10 /100, '$999G999G999' )AS "BONIFICACIÓN"
FROM EMPLEADO
WHERE RUN_JEFE IS NOT NULL
GROUP BY RUN_JEFE;

--CASO 4
SELECT 
    ID_ESCOLARIDAD AS "ESCOLARIDAD",
    (CASE WHEN ID_ESCOLARIDAD = 10  THEN 'BÁSICA'
    WHEN ID_ESCOLARIDAD = 20  THEN 'MEDIA CIENTÍFICA HUMANISTA'
    WHEN ID_ESCOLARIDAD = 30  THEN 'MEDIA TÉCNICO PROFESIONAL'
    WHEN ID_ESCOLARIDAD = 40  THEN 'SUPERIOR CENTRO DE FORMACIÓN TÉCNICA'
    WHEN ID_ESCOLARIDAD = 50  THEN 'SUPERIOR INSTITUTO PROFESIONAL' 
    WHEN ID_ESCOLARIDAD = 60  THEN 'SUPERIOR UNIVERSIDAD' END) AS "DESCRIPCIÓN ESCOLARIDAD",
    COUNT(RUN_EMP) "TOTAL EMPLEADOS",
    TO_CHAR(MAX(SALARIO),'$999G999G999') AS "SALARIO MAXIMO",
    TO_CHAR(MIN(SALARIO),'$999G999G999') AS "SALARIO MINIMO",
    TO_CHAR(SUM(SALARIO), '$999G999G999') AS "SALARIO TOTAL",
    TO_CHAR(ROUND(AVG(SALARIO)),'$999G999G999') AS "SALARIO PROMEDIO"
FROM EMPLEADO
GROUP BY ID_ESCOLARIDAD
ORDER BY COUNT(RUN_EMP) DESC;

--CASO 5
SELECT
    TITULOID AS "CODIGO DEL LIBRO",
    COUNT(EJEMPLARID) AS "TOTAL DE VECES SOLICITADO",
    (CASE WHEN COUNT(EJEMPLARID) = 1 THEN 'No se requiere nuevos ejemplares'
    WHEN COUNT(EJEMPLARID) BETWEEN 2 AND 3 THEN 'Se requiere comprar 1 nuevos ejemplares'
    WHEN COUNT(EJEMPLARID) BETWEEN 4 AND 5 THEN 'Se requiere comprar 2 nuevos ejemplares'
    WHEN COUNT(EJEMPLARID) > 5 THEN 'Se requiere comprar 4 nuevos ejemplares'END) AS "SUGERENCIA"
FROM PRESTAMO 
WHERE EXTRACT(YEAR FROM FECHA_INI_PRESTAMO)=2021
GROUP BY TITULOID
ORDER BY COUNT(EJEMPLARID) DESC;

--CASO 6
SELECT 
    TO_CHAR(RUN_EMP,'99G999G999') AS "RUN EMPLEADO",
    TO_CHAR (FECHA_INI_PRESTAMO, 'mm/yyyy') AS "MES PRESTAMO LIBRO",
    COUNT(RUN_EMP) AS "TOTAL PRESTAMOS ATENDIDOS",
    TO_CHAR(COUNT(RUN_EMP) * 10000, '$999G999G999') AS "ASIGNACION POR PRESTAMOS"
FROM PRESTAMO 
WHERE EXTRACT(YEAR FROM FECHA_INI_PRESTAMO) IN 2021 
HAVING COUNT(RUN_EMP) > 2
GROUP BY RUN_EMP,TO_CHAR (FECHA_INI_PRESTAMO, 'mm/yyyy')
ORDER BY TO_CHAR (FECHA_INI_PRESTAMO, 'mm/yyyy'),TO_CHAR(COUNT(RUN_EMP) * 10000, '$999G999G999') DESC,TO_CHAR(RUN_EMP,'99G999G999') DESC ;