-CASO 1
SELECT
    TO_CHAR (FECHA_ENTREGA_PROPIEDAD, 'dd/mm/yyyy') AS "FECHA ENTREGA PROPIEDAD"
FROM PROPIEDAD
WHERE EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD)= 2022
ORDER BY EXTRACT(MONTH FROM FECHA_ENTREGA_PROPIEDAD) ASC;
--CASO 2
SELECT
    TO_CHAR (FECINI_ARRIENDO, 'dd/mm/yyyy') AS "FECHA INICIO ARRIENDO"
FROM PROPIEDAD_ARRENDADA
WHERE EXTRACT(YEAR FROM FECINI_ARRIENDO)= 2022
ORDER BY EXTRACT (MONTH FROM FECINI_ARRIENDO) ASC;
-------------------------
--2
SELECT
    NUMRUT_CLI ||'-'||
    DVRUT_CLI AS "RUT CLIENTE",
    NOMBRE_CLI ||' '|| 
    APPATERNO_CLI ||' '|| 
    APMATERNO_CLI AS "NOMBRE CLIENTE",
    RENTA_CLI AS "RENTA",
    FONOFIJO_CLI AS "TELEFONO FIJO",
    CELULAR_CLI AS "CELULAR"
FROM CLIENTE
WHERE ID_ESTCIVIL IN(1, 3, 4) AND RENTA_CLI >= 800000
ORDER BY APPATERNO_CLI;
--------------------------
--3
--SIMULACIÓN 1
SELECT
     NOMBRE_EMP||' '||
     APPATERNO_EMP||' '||
     APMATERNO_EMP AS "NOMBRE EMPLEADO",
     SUELDO_EMP AS "SUELDO ACTUAL",
     SUELDO_EMP * 108.5/100 AS "SUELDO REAJUSTADO",
     SUELDO_EMP * 8.5/100 AS "AUMENTO"
FROM EMPLEADO
ORDER BY SUELDO_EMP * 8.5/100 DESC;
--SIMULACIÓN 2
SELECT
     NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
     SUELDO_EMP AS "SUELDO ACTUAL",
     SUELDO_EMP * 120/100 AS "SUELDO REAJUSTADO",
     SUELDO_EMP * 20/100 AS "AUMENTO"
FROM EMPLEADO
WHERE SUELDO_EMP BETWEEN 200000 AND 400000
ORDER BY SUELDO_EMP * 20/100 DESC;
----------------------------
--4
SELECT
    NUMRUT_EMP ||'-'|| 
    DVRUT_EMP AS "RUN EMPLEADO",
    NOMBRE_EMP||' '||
    APPATERNO_EMP||' '||
    APMATERNO_EMP AS "NOMBRE EMPLEADO",
    SUELDO_EMP AS "SALARIO ACTUAL",
    SUELDO_EMP * &BONIFICACION/100 AS "BONIFICACION EXTRA"
FROM EMPLEADO
WHERE SUELDO_EMP < 500000
ORDER BY APPATERNO_EMP;
----------------------------
--5
--Prueba N°1 del informe
SELECT
    NRO_PROPIEDAD AS "NUMERO PROPIEDAD",
    TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION PROPIEDAD",
    SUPERFICIE,
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD)=2022
ORDER BY FECHA_ENTREGA_PROPIEDAD ASC;

--Prueba N°2 del informe
SELECT
    NRO_PROPIEDAD AS "NUMERO PROPIEDAD",
    TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION PROPIEDAD",
    SUPERFICIE,
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD)=2010
ORDER BY FECHA_ENTREGA_PROPIEDAD ASC;

--TABLA DET_PROPIEDADES_ARRIENDO_VENTA
CREATE TABLE DET_PROPIEDADES_ARRIENDO_VENTA
    AS SELECT * FROM PROPIEDAD;

SELECT
    NRO_PROPIEDAD AS "NUMERO PROPIEDAD",
    TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION PROPIEDAD",
    SUPERFICIE,
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM DET_PROPIEDADES_ARRIENDO_VENTA
WHERE EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD)=2022
ORDER BY FECHA_ENTREGA_PROPIEDAD ASC;