--CASO 1

SELECT
    TO_CHAR(cli.NUMRUN,'99G999G999')||'-'||
    cli.DVRUN AS "RUN CLIENTE",
    cli.PNOMBRE || ' ' ||
    cli.SNOMBRE || ' ' ||
    cli.APPATERNO || ' ' ||
    cli.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(cli.FECHA_NACIMIENTO, 'DD "de" Month') AS "DIA DE CUMPLEAÑOS",
    SR.DIRECCION AS "SUCURSAL"
FROM cliente cli
    JOIN comuna com ON cli.cod_comuna = com.cod_comuna AND cli.cod_provincia = com.cod_provincia AND cli.cod_region = com.cod_region
    JOIN sucursal_retail sr ON com.cod_comuna = sr.cod_comuna AND sr.cod_provincia = com.cod_provincia AND sr.cod_region = com.cod_region
    ORDER BY "DIA DE CUMPLEAÑOS" ASC, cli.APPATERNO;

--CASO 2

SELECT
    TO_CHAR(cli.NUMRUN,'99G999G999')||'-'||
    cli.DVRUN AS "RUN CLIENTE",
    cli.PNOMBRE || ' ' ||
    cli.SNOMBRE || ' ' ||
    cli.APPATERNO || ' ' ||
    cli.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(SUM(TTC.MONTO_TRANSACCION), '$99G999G999') AS "MONTO COMPRAS/AVANCES/S.AVANCES",
    TO_CHAR(ROUND((SUM(TTC.MONTO_TRANSACCION)/10000)*250), '999G999') AS "TOTAL PUNTOS ACUMULADOS"
FROM CLIENTE cli 
    JOIN TARJETA_CLIENTE tc ON (cli.NUMRUN = tc.NUMRUN)
    JOIN TRANSACCION_TARJETA_CLIENTE ttc ON (tc.NRO_TARJETA = ttc.NRO_TARJETA)
WHERE EXTRACT(YEAR FROM ttc.FECHA_TRANSACCION) = EXTRACT(YEAR FROM SYSDATE)-1
GROUP BY CLI.NUMRUN, CLI.DVRUN, CLI.PNOMBRE, CLI.SNOMBRE, CLI.APPATERNO, CLI.APMATERNO
ORDER BY "TOTAL PUNTOS ACUMULADOS", CLI.APPATERNO;

--CASO 3

SELECT
    TO_CHAR(TTC.FECHA_TRANSACCION, 'MMYYYY') AS "MES TRANSACCIÓN",
    ttt.NOMBRE_TPTRAN_TARJETA AS "TIPO TRANSACCION",
    TO_CHAR(SUM(ttc.MONTO_TOTAL_TRANSACCION), '$999G999G999') AS "MONTO AVANCES/SUPER AVANCES",
    TO_CHAR((aps.PORC_APORTE_SBIF/100)* SUM(ttc.MONTO_TOTAL_TRANSACCION), '$999G999G999') AS "APORTE A LA SBIF"
FROM TRANSACCION_TARJETA_CLIENTE ttc
    JOIN TIPO_TRANSACCION_TARJETA ttt ON (ttc.COD_TPTRAN_TARJETA = ttt.COD_TPTRAN_TARJETA)
    JOIN APORTE_SBIF aps ON ttc.MONTO_TOTAL_TRANSACCION BETWEEN aps.MONTO_INF_AV_SAV AND aps.MONTO_SUP_AV_SAV
WHERE TTT.COD_TPTRAN_TARJETA IN(103, 102) AND
      EXTRACT(YEAR FROM ttc.FECHA_TRANSACCION) = EXTRACT(YEAR FROM SYSDATE) AND
      ttc.MONTO_TOTAL_TRANSACCION >= 100000
GROUP BY TO_CHAR(TTC.FECHA_TRANSACCION, 'MMYYYY'), ttt.NOMBRE_TPTRAN_TARJETA,aps.PORC_APORTE_SBIF
ORDER BY "MES TRANSACCIÓN";

--3.1

SELECT
    TO_CHAR(TTC.FECHA_TRANSACCION, 'MMYYYY') AS "MES TRANSACCION",
    TTT.NOMBRE_TPTRAN_TARJETA AS "TIPO TRANSACCION",
    TO_CHAR(SUM(TTC.MONTO_TOTAL_TRANSACCION), '$999G999G999') AS "MONTO AVANCES/SUPER AVANCES",
    (CASE WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) < 100000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0), '$999G999') 
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 100000 AND 1000000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.01), '$999G999')
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 1000001 AND 2000000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.02), '$999G999')
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 2000001 AND 4000000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.03), '$999G999')
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 4000001 AND 6000000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.04), '$999G999')
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 6000001 AND 9999999999 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.07), '$999G999') END) AS "APORTE SBIF"
FROM TRANSACCION_TARJETA_CLIENTE TTC JOIN TIPO_TRANSACCION_TARJETA TTT ON (TTC.COD_TPTRAN_TARJETA = TTT.COD_TPTRAN_TARJETA)
WHERE TTT.COD_TPTRAN_TARJETA IN(103, 102) AND
      EXTRACT(YEAR FROM ttc.FECHA_TRANSACCION) = EXTRACT(YEAR FROM SYSDATE) AND
      ttc.MONTO_TOTAL_TRANSACCION >= 100000
GROUP BY TO_CHAR(TTC.FECHA_TRANSACCION, 'MMYYYY'), TTT.NOMBRE_TPTRAN_TARJETA
ORDER BY "MES TRANSACCION", "TIPO TRANSACCION";

--CASO 4

SELECT 
    TO_CHAR(cli.NUMRUN,'99G999G999')||'-'||
    cli.DVRUN AS "RUN CLIENTE",
    cli.PNOMBRE || ' ' ||
    cli.SNOMBRE || ' ' ||
    cli.APPATERNO || ' ' ||
    cli.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(SUM(ttc.MONTO_TOTAL_TRANSACCION), '$999G999G999') AS "MONTO AVANCES/SUPER AVANCES",
    (CASE WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION BETWEEN 0 and 99999 THEN 'SIN CATEGORIZACION'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) BETWEEN 100000 and 1000000 THEN 'BRONCE'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) BETWEEN 1000001 and 4000000 THEN 'PLATA'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) BETWEEN 4000001 and 8000000 THEN 'SILVER'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) BETWEEN 8000001 and 15000000 THEN 'GOLD'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) > 15000000 THEN 'PATINUM' END) AS "CATEGORIA CLIENTE"
FROM CLIENTE cli 
    JOIN TARJETA_CLIENTE tc ON (cli.numrun = tc.numrun)
    JOIN TRANSACCION_TARJETA_CLIENTE ttc ON (tc.NRO_TARJETA = ttc.NRO_TARJETA)
GROUP BY cli.NUMRUN, cli.DVRUN, cli.PNOMBRE, cli.SNOMBRE, cli.APPATERNO, cli.APMATERNO;