--1
SELECT
    NOMBRE_EMP|| ' ' ||
    APPATERNO_EMP||' ' ||
    APMATERNO_EMP||' ' ||
    TO_CHAR (FECNAC_EMP, 'dd/mm/yyyy') AS "LISTADO DE CUMPLEAÑOS"
FROM empleado
ORDER BY FECNAC_EMP ASC, APPATERNO_EMP DESC;

--2
SELECT
    NUMRUT_CLI AS "NUMERO RUT",
    DVRUT_CLI AS "DIGITO VERIFICADOR",
    APPATERNO_CLI|| ' ' ||
    APMATERNO_CLI|| ' ' ||
    NOMBRE_CLI AS "NOMBRE CLIENTE",
    RENTA_CLI AS "RENTA",
    FONOFIJO_CLI AS "TELEFONO FIJO",
    CELULAR_CLI AS "CELULAR"
FROM cliente
ORDER BY APPATERNO_CLI ASC, APMATERNO_CLI ASC;

--3
SELECT
    NOMBRE_EMP|| ' ' ||
    APPATERNO_EMP||' ' ||
    APMATERNO_EMP AS "Nombre Completo",
    SUELDO_EMP,
    SUELDO_EMP/2 AS "Bono Por Capacitación"
FROM empleado
ORDER BY SUELDO_EMP/2 DESC;

--4
SELECT 
    NRO_PROPIEDAD AS "NRO PROPIEDAD",
    NUMRUT_PROP AS "RUT PROPIETARIO",
    DIRECCION_PROPIEDAD AS "DIRECCIÓN",
    VALOR_ARRIENDO AS "VALOR ARRIENDO",
    VALOR_ARRIENDO*0.054 AS "VALOR COMPENSACION"
FROM propiedad
ORDER BY NUMRUT_PROP ASC;

--5
SELECT
    NUMRUT_EMP AS "RUN EMPLEADO",
    NOMBRE_EMP|| ' ' ||
    APPATERNO_EMP||' ' ||
    APMATERNO_EMP AS "Nombre EMPLEADO",
    SUELDO_EMP AS "SALARIO ACTUAL",
    SUELDO_EMP*113.5/100 AS "SALARIO REAJUSTADO",
    SUELDO_EMP*13.5/100 AS "REAJUSTE"
FROM empleado
ORDER BY SUELDO_EMP*113.5 DESC, APPATERNO_EMP DESC;

--6
SELECT
    NOMBRE_EMP|| ' ' ||
    APPATERNO_EMP AS "Nombre Y Apellido",
    SUELDO_EMP AS "Salario",
    SUELDO_EMP*5.5/100 AS "Colación",
    SUELDO_EMP*17.8/100 AS "Movilización",
    SUELDO_EMP*7.8/100 AS "Salud",
    SUELDO_EMP*6.5/100 AS "AFP",
    SUELDO_EMP + SUELDO_EMP*5.5/100 + SUELDO_EMP*17.8/100 - SUELDO_EMP*7.8/100 - SUELDO_EMP*6.5/100 AS "Alcance Líquido"
FROM empleado
ORDER BY APPATERNO_EMP ASC;    